# Site settings
title: "Data Science & Analytics Projects"
description: "Showcasing my work in Power BI, Python, and data analysis."
theme: jekyll-theme-minimal
google_analytics: "G-1N3HBP1NTX"  # Your Google Analytics ID
linkedin: https://www.linkedin.com/in/09barbosacarlos

# Add this if you already have other plugins
plugins:
  - jekyll-seo-tag

# Optional: Add custom logo
logo: "/assets/images/logo.png"  # Path to your logo image
markdown: kramdown
